models = [
    {
        "model_name": "gpt-4-0125-preview",
        "input_tokens": 128000,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-4-turbo-preview",
        "input_tokens": 128000,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-4-1106-preview",
        "input_tokens": 128000,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-4-vision-preview",
        "input_tokens": 128000,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-4-1106-vision-preview",
        "input_tokens": 128000,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-4",
        "input_tokens": 8192,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-4-0613",
        "input_tokens": 8192,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-4-32k",
        "input_tokens": 32768,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-4-32k-0613",
        "input_tokens": 32768,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-3.5-turbo-0125",
        "input_tokens": 16385,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-3.5-turbo",
        "input_tokens": 4096,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-3.5-turbo-1106",
        "input_tokens": 16385,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-3.5-turbo-instruct",
        "input_tokens": 4096,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-3.5-turbo-16k",
        "input_tokens": 16385,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-3.5-turbo-0613",
        "input_tokens": 4096,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gpt-3.5-turbo-16k-0613",
        "input_tokens": 16385,
        "output_tokens": 4096,
        "api_name": "OpenAI API",
    },
    {
        "model_name": "gemini-1.5-pro-latest",
        "input_token": 1048576,
        "output_token": 8192,
        "api_name": "Gemini API",
    },
    {
        "model_name": "gemini-1.0-pro",
        "input_token": 30720,
        "output_token": 2048,
        "api_name": "Gemini API",
    },
    {
        "model_name": "gemini-1.0-pro-001",
        "input_token": 30720,
        "output_token": 2048,
        "api_name": "Gemini API",
    },
    {
        "model_name": "gemini-1.0-pro-latest",
        "input_token": 30720,
        "output_token": 2048,
        "api_name": "Gemini API",
    },
    {
        "model_name": "gemini-1.0-pro-vision-latest",
        "input_token": 12288,
        "output_token": 4096,
        "api_name": "Gemini API",
    },
    {
        "model_name": "gemini-pro",
        "input_token": 30720,
        "output_token": 2048,
        "api_name": "Gemini API",
    },
    {
        "model_name": "gemini-pro-vision",
        "input_token": 12288,
        "output_token": 4096,
        "api_name": "Gemini API",
    },
    {
        "model_name": "command-light",
        "input_token": 4096,
        "api_name": "Cohere API",
    },
    {
        "model_name": "command-light-nightly",
        "input_token": 8192,
        "api_name": "Cohere API",
    },
    {
        "model_name": "command",
        "input_token": 4096,
        "api_name": "Cohere API",
    },
    {
        "model_name": "command-nightly",
        "input_token": 8192,
        "api_name": "Cohere API",
    },
    {
        "model_name": "claude-3-opus-20240229",
        "input_tokens": 200000,
        "output_tokens": 4096,
        "api_name": "Claude API",
    },
    {
        "model_name": "claude-3-sonnet-20240229",
        "input_tokens": 200000,
        "output_tokens": 4096,
        "api_name": "Claude API",
    },
    {
        "model_name": "claude-3-haiku-20240307",
        "input_tokens": 200000,
        "output_tokens": 4096,
        "api_name": "Claude API",
    },
    {
        "model_name": "claude-2.1",
        "input_tokens": 200000,
        "output_tokens": 4096,
        "api_name": "Claude API",
    },
    {
        "model_name": "claude-2.0",
        "input_tokens": 100000,
        "output_tokens": 4096,
        "api_name": "Claude API",
    },
    {
        "model_name": "claude-instant-1.2",
        "input_tokens": 100000,
        "output_tokens": 4096,
        "api_name": "Claude API",
    },
    {
        "model_name": "llama2-70b-4096",
        "input_tokens": 4096,
        "output_tokens": 4096,
        "api_name": "groq API",
    },
    {
        "model_name": "mixtral-8x7b-32768",
        "input_tokens": 32768,
        "output_tokens": 32768,
        "api_name": "groq API",
    },
    {
        "model_name": "gemma-7b-it",
        "input_tokens": 8192,
        "output_tokens": 8192,
        "api_name": "groq API",
    },
]
